assign_WIDTH <- function(eflalo, LE_MET) {
  eflalo$LE_WIDTH <-0
  eflalo$LE_WIDTH  <- ifelse(grepl("DRB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET), 6.096, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("DRB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET), 9.144, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("DRB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET), 9.144, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("CEP", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 76.2, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("CEP", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 45.72, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("CEP", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 106.68, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("CEP", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 45.72, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("CEP", eflalo$LE_MET)& grepl("South", eflalo$LE_MET),121.92, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("CEP", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 45.72, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("LEM", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 76.2, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("LEM", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 45.72, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("LEM", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 106.68, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("LEM", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 45.72, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("LEM", eflalo$LE_MET)& grepl("South", eflalo$LE_MET),121.92, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("LEM", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 45.72, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("DEF", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("DEF", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 30.48, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("DEF", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 76.2, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("DEF", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 38.1, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("DEF", eflalo$LE_MET)& grepl("South", eflalo$LE_MET),76.2, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("DEF", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 38.1, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("CRU", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("CRU", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 30.48, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("CRU", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 76.2, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("CRU", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 38.1, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("CRU", eflalo$LE_MET)& grepl("South", eflalo$LE_MET),76.2, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("CRU", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 38.1, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("SPF", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("SPF", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 30.48, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("SPF", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 76.2, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("SPF", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 38.1, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("SPF", eflalo$LE_MET)& grepl("South", eflalo$LE_MET),76.2, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("SPF", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 38.1, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("MIX", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("MIX", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 30.48, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("MIX", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 76.2, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("MIX", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 38.1, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("MIX", eflalo$LE_MET)& grepl("South", eflalo$LE_MET),76.2, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("MIX", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 38.1, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("MOL", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 12.192, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("MOL", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 12.192, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("MOL", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 12.192, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("MOL", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 12.192, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("MOL", eflalo$LE_MET)& grepl("South", eflalo$LE_MET),18.288, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("MOL", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 18.288, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("CEP", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 121.92, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("CEP", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("CEP", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 182.88, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("CEP", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("CEP", eflalo$LE_MET)& grepl("South", eflalo$LE_MET),228.6, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("CEP", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("LEM", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 121.92, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("LEM", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("LEM", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 182.88, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("LEM", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("LEM", eflalo$LE_MET)& grepl("South", eflalo$LE_MET),228.6, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("LEM", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("DEF", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 91.44, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("DEF", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("DEF", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 137.16, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("DEF", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("DEF", eflalo$LE_MET)& grepl("South", eflalo$LE_MET),137.16, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("DEF", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("MIX", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 91.44, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("MIX", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("MIX", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 137.16, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("MIX", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("MIX", eflalo$LE_MET)& grepl("South", eflalo$LE_MET),137.16, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("MIX", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("CRU", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 91.44, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET)& grepl("CRU", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("CRU", eflalo$LE_MET)& grepl("South", eflalo$LE_MET), 137.16, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET)& grepl("CRU", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("CRU", eflalo$LE_MET)& grepl("South", eflalo$LE_MET),137.16, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET)& grepl("CRU", eflalo$LE_MET)& grepl("Other", eflalo$LE_MET), 60.96, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("PTB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET), 92.5, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("PTB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET), 137.5, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("TBB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET), 8, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("TBB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET), 14, eflalo$LE_WIDTH)
  eflalo$LE_WIDTH  <- ifelse(grepl("TBB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET), 24, eflalo$LE_WIDTH)
  return(eflalo)}

assign_subsurface_abrasion <- function(eflalo, LE_MET) {
  eflalo$LE_SUB <-0
  eflalo$LE_SUB  <- ifelse(grepl("DRB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET), 6.096, eflalo$LE_SUB)
  eflalo$LE_SUB  <- ifelse(grepl("DRB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET), 9.144, eflalo$LE_SUB)
  eflalo$LE_SUB  <- ifelse(grepl("DRB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET), 9.144, eflalo$LE_SUB)
  eflalo$LE_SUB  <- ifelse(grepl("TBB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET), 8, eflalo$LE_SUB)
  eflalo$LE_SUB  <- ifelse(grepl("TBB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET), 14, eflalo$LE_SUB)
  eflalo$LE_SUB  <- ifelse(grepl("TBB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET), 24, eflalo$LE_SUB)
  eflalo$LE_SUB  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET), 1.52, eflalo$LE_SUB)
  eflalo$LE_SUB  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET), 2.13, eflalo$LE_SUB)
  eflalo$LE_SUB  <- ifelse(grepl("OTB", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET), 2.44, eflalo$LE_SUB)
  eflalo$LE_SUB  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("SMA", eflalo$LE_MET), 2.13, eflalo$LE_SUB)
  eflalo$LE_SUB  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("MED", eflalo$LE_MET), 2.74, eflalo$LE_SUB)
  eflalo$LE_SUB  <- ifelse(grepl("OTT", eflalo$LE_MET) & grepl("LAR", eflalo$LE_MET), 3.20, eflalo$LE_SUB)
  return(eflalo)}
